import type { ProductData } from "./types";

export const tabela: ProductData[] = [
  //Car Parts
  {
    id: "carA123XYZ",
    name: "Bosch Spark Plug FR7",
    detail:
      "High-performance spark plug ensuring better ignition and mileage. Compatible with most petrol cars.",
    category: "car",
    rating: 4.7,
    price: 12.99,
    image: "https://placehold.co/300",
    brand: "Bosch",
    inStock: true,
  },
  {
    id: "carB456LMN",
    name: "Delphi Fuel Injector",
    detail:
      "Precision-engineered fuel injector with high flow rate and efficient spray pattern.",
    category: "car",
    rating: 4.5,
    price: 89.5,
    image: "https://placehold.co/300",
    brand: "Delphi",
    inStock: true,
  },
  {
    id: "carC789OPQ",
    name: "Valeo Clutch Kit",
    detail:
      "Durable clutch kit for smooth gear transitions and extended lifecycle.",
    category: "car",
    rating: 4.6,
    price: 145.0,
    image: "https://placehold.co/300",
    brand: "Valeo",
    inStock: true,
  },
  {
    id: "carD012RST",
    name: "Monroe Shock Absorbers",
    detail: "Gas-charged shock absorbers for better handling and ride comfort.",
    category: "car",
    rating: 4.4,
    price: 75.2,
    image: "https://placehold.co/300",
    brand: "Monroe",
    inStock: true,
  },
  {
    id: "carE345UVW",
    name: "MANN Air Filter",
    detail:
      "High-efficiency air filter for enhanced engine performance and cleaner air intake.",
    category: "car",
    rating: 4.9,
    price: 19.99,
    image: "https://placehold.co/300",
    brand: "MANN",
    inStock: true,
  },
  {
    id: "carF678XYZ",
    name: "Bosch Brake Pads Set",
    detail:
      "Reliable braking performance with low dust and noise. Long life guaranteed.",
    category: "car",
    rating: 4.8,
    price: 55.0,
    image: "https://placehold.co/300",
    brand: "Bosch",
    inStock: true,
  },
  {
    id: "carG901ABC",
    name: "NGK Ignition Coil",
    detail:
      "OEM-grade ignition coil providing better start-up and fuel efficiency.",
    category: "car",
    rating: 4.6,
    price: 34.75,
    image: "https://placehold.co/300",
    brand: "NGK",
    inStock: false,
  },
  {
    id: "carH234DEF",
    name: "Continental Timing Belt",
    detail:
      "High-quality timing belt for quiet operation and long-lasting performance.",
    category: "car",
    rating: 4.5,
    price: 72.0,
    image: "https://placehold.co/300",
    brand: "Continental",
    inStock: true,
  },
  {
    id: "carI567GHI",
    name: "Castrol EDGE 5W-30",
    detail:
      "Premium full synthetic oil that maximizes short and long-term engine performance.",
    category: "car",
    rating: 4.9,
    price: 42.0,
    image: "https://placehold.co/300",
    brand: "Castrol",
    inStock: true,
  },
  {
    id: "carJ890JKL",
    name: "Hella Headlamp Assembly",
    detail:
      "OEM-grade headlamp with high brightness and reliable housing for better road visibility.",
    category: "car",
    rating: 4.3,
    price: 110.0,
    image: "https://placehold.co/300",
    brand: "Hella",
    inStock: true,
  },

  // Bike Parts
  {
    id: "bikeA123DEF",
    name: "Motul 7100 4T 10W40 Oil",
    detail:
      "Fully synthetic motorcycle oil for superior engine protection and smoother gear shifts.",
    category: "bike",
    rating: 4.8,
    price: 18.49,
    image: "https://placehold.co/300",
    brand: "Motul",
    inStock: true,
  },
  {
    id: "bikeB456GHI",
    name: "NGK Iridium Spark Plug",
    detail:
      "Improves ignition efficiency and throttle response for most bikes.",
    category: "bike",
    rating: 4.7,
    price: 9.99,
    image: "https://placehold.co/300",
    brand: "NGK",
    inStock: true,
  },
  {
    id: "bikeC789JKL",
    name: "Brembo Brake Pads",
    detail:
      "Top-quality braking system upgrade for enhanced safety and precision.",
    category: "bike",
    rating: 4.6,
    price: 35.0,
    image: "https://placehold.co/300",
    brand: "Brembo",
    inStock: true,
  },
  {
    id: "bikeD012MNO",
    name: "RK Racing Chain Kit",
    detail:
      "High-performance chain kit with increased durability for sport and street bikes.",
    category: "bike",
    rating: 4.5,
    price: 49.0,
    image: "https://placehold.co/300",
    brand: "RK Racing",
    inStock: true,
  },
  {
    id: "bikeE345PQR",
    name: "Pirelli Sport Demon Tyre",
    detail: "Superior grip and handling for high-performance motorcycles.",
    category: "bike",
    rating: 4.8,
    price: 79.99,
    image: "https://placehold.co/300",
    brand: "Pirelli",
    inStock: true,
  },
  {
    id: "bikeF678STU",
    name: "K&N Performance Air Filter",
    detail: "Reusable high-flow air filter designed to increase horsepower.",
    category: "bike",
    rating: 4.7,
    price: 29.99,
    image: "https://placehold.co/300",
    brand: "K&N",
    inStock: true,
  },
  {
    id: "bikeG901VWX",
    name: "Osram LED Headlight Bulb",
    detail:
      "Bright white LED lighting with low power consumption and long life.",
    category: "bike",
    rating: 4.4,
    price: 22.0,
    image: "https://placehold.co/300",
    brand: "Osram",
    inStock: true,
  },
  {
    id: "bikeH234YZA",
    name: "Yamaha Clutch Plate Kit",
    detail:
      "OEM replacement kit offering smooth and consistent clutch performance.",
    category: "bike",
    rating: 4.5,
    price: 39.0,
    image: "https://placehold.co/300",
    brand: "Yamaha",
    inStock: false,
  },
  {
    id: "bikeI567BCD",
    name: "EBC Brake Disc Rotor",
    detail: "Heat-treated rotor for high-performance braking and long life.",
    category: "bike",
    rating: 4.6,
    price: 58.99,
    image: "https://placehold.co/300",
    brand: "EBC",
    inStock: true,
  },
  {
    id: "bikeJ890EFG",
    name: "Royal Enfield Mirror Set",
    detail:
      "Classic round mirrors with chrome finish compatible with most RE models.",
    category: "bike",
    rating: 4.2,
    price: 14.49,
    image: "https://placehold.co/300",
    brand: "Royal Enfield",
    inStock: true,
  },

  // Jet Engine Parts
  {
    id: "jetA1234567",
    name: "Turbine Blade Set",
    detail: "Precision-forged turbine blades for modern turbofan engines.",
    category: "jet",
    rating: 4.9,
    price: 8500.0,
    image: "https://placehold.co/300",
    brand: "GE Aviation",
    inStock: true,
  },
  {
    id: "jetB2345678",
    name: "Jet Engine Oil Filter",
    detail:
      "High-capacity filter designed for use in military and commercial engines.",
    category: "jet",
    rating: 4.7,
    price: 320.0,
    image: "https://placehold.co/300",
    brand: "Rolls-Royce",
    inStock: true,
  },
  {
    id: "jetC3456789",
    name: "Fuel Nozzle Assembly",
    detail:
      "Advanced nozzle providing optimal atomization for efficient combustion.",
    category: "jet",
    rating: 4.8,
    price: 950.0,
    image: "https://placehold.co/300",
    brand: "Honeywell",
    inStock: false,
  },
  {
    id: "jetD4567890",
    name: "Compressor Stator Vane",
    detail:
      "Aerodynamically designed vane for jet engine compressor stage, ensuring smooth airflow.",
    category: "jet",
    rating: 4.6,
    price: 1120.0,
    image: "https://placehold.co/300",
    brand: "Pratt & Whitney",
    inStock: true,
  },
  {
    id: "jetE5678901",
    name: "Ignition Exciter Box",
    detail:
      "High-energy igniter unit used in turbine engines to start combustion.",
    category: "jet",
    rating: 4.7,
    price: 1450.0,
    image: "https://placehold.co/300",
    brand: "Safran",
    inStock: true,
  },
  {
    id: "jetF6789012",
    name: "Jet Engine Temperature Sensor",
    detail: "Precise EGT sensor for monitoring turbine temperatures in flight.",
    category: "jet",
    rating: 4.5,
    price: 640.0,
    image: "https://placehold.co/300",
    brand: "Honeywell",
    inStock: true,
  },
  {
    id: "jetG7890123",
    name: "Hydraulic Actuator Valve",
    detail:
      "Critical control system component used in aircraft engine thrust vectoring.",
    category: "jet",
    rating: 4.6,
    price: 1250.0,
    image: "https://placehold.co/300",
    brand: "Moog",
    inStock: false,
  },
  {
    id: "tractA123456",
    name: "John Deere Oil Filter",
    detail:
      "OEM-grade filter ensuring clean oil circulation for tractors under heavy load.",
    category: "tractor",
    rating: 4.8,
    price: 19.99,
    image: "https://placehold.co/300",
    brand: "John Deere",
    inStock: true,
  },
  {
    id: "tractB234567",
    name: "Tractor PTO Shaft",
    detail:
      "Durable power take-off shaft for transmission of rotary power from tractor to implement.",
    category: "tractor",
    rating: 4.7,
    price: 149.0,
    image: "https://placehold.co/300",
    brand: "Mahindra",
    inStock: true,
  },
  {
    id: "tractC345678",
    name: "Hydraulic Lift Pump",
    detail:
      "Essential component for raising and lowering agricultural implements with ease.",
    category: "tractor",
    rating: 4.5,
    price: 98.75,
    image: "https://placehold.co/300",
    brand: "Swaraj",
    inStock: true,
  },
  {
    id: "tractD456789",
    name: "Tractor Steering Box Assembly",
    detail:
      "Heavy-duty steering unit for precise maneuvering in farming conditions.",
    category: "tractor",
    rating: 4.4,
    price: 160.0,
    image: "https://placehold.co/300",
    brand: "TAFE",
    inStock: false,
  },
  {
    id: "tractE567890",
    name: "Clutch Plate for Farm Tractor",
    detail:
      "High-friction clutch plate designed for frequent stop-start field operations.",
    category: "tractor",
    rating: 4.6,
    price: 85.0,
    image: "https://placehold.co/300",
    brand: "Eicher",
    inStock: true,
  },
];
